"""initial migrations

Revision ID: 16832701de13
Revises: 
Create Date: 2022-03-15 15:41:42.676509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16832701de13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('premium_user', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
