"""premium user view

Revision ID: 3616185160fd
Revises: 16832701de13
Create Date: 2022-03-15 17:26:18.705033

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '3616185160fd'
down_revision = '16832701de13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_premium_views = PGView(
        schema="public",
        signature="premium_views",
        definition='SELECT * FROM "user" WHERE premium_user IS TRUE'
    )
    op.create_entity(public_premium_views)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_premium_views = PGView(
        schema="public",
        signature="premium_views",
        definition='SELECT * FROM "user" WHERE premium_user IS TRUE'
    )
    op.drop_entity(public_premium_views)

    # ### end Alembic commands ###
