"""premium user view

Revision ID: f31f425533a8
Revises: 16832701de13
Create Date: 2022-03-15 17:36:23.215408

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'f31f425533a8'
down_revision = '16832701de13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_premium_users = PGView(
        schema="public",
        signature="premium_users",
        definition='SELECT * FROM "user" WHERE premium_user IS TRUE'
    )
    op.create_entity(public_premium_users)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_premium_users = PGView(
        schema="public",
        signature="premium_users",
        definition='SELECT * FROM "user" WHERE premium_user IS TRUE'
    )
    op.drop_entity(public_premium_users)

    # ### end Alembic commands ###
